In [ ]:
import tensorflow as tf
a = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32) # Create a 2x2 matrix with values 1, 2, 3, and 4.
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
#View common attributes.
print("value of the constant const_a:", const_a.numpy())
print("data type of the constant const_a:", const_a.dtype)
print("shape of the constant const_a:", const_a.shape)
print("name of the device that is to generate the constant const_a:", const_a.device)

value of the constant const_a: [[1. 2.]
 [3. 4.]]
data type of the constant const_a: <dtype: 'float32'>
shape of the constant const_a: (2, 2)
name of the device that is to generate the constant const_a: /job:localhost/replica:0/task:0/device:CPU:0


In [ ]:
b = tf.zeros(shape=[2, 3], dtype=tf.int32) # Create a 2x3 matrix with all values being 0.
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
zeros_like_c = tf.zeros_like(a)
zeros_like_c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
fill_d = tf.fill([3,3], 8) # Create a 2x3 matrix with all values being 8.

fill_d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int32)>

In [ ]:
random_e = tf.random.normal([5,5],mean=0,stddev=1.0, seed = 1)
#View the created data.
random_e

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)>

In [ ]:
#Create a list.
f = [1,2,3,4,5,6]
#View the data type.
type(f)

list

In [ ]:
list_f

[1, 2, 3, 4, 5, 6]

In [ ]:
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [ ]:
#Create a variable. Only the initial value needs to be provided.
var_1 = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
#Read the variable value.
print("Value of the variable var_1:",var_1.read_value())
#Assign a variable value.
var_value_1=[[1,2,3],[4,5,6]]
var_1.assign(var_value_1)
print("Value of the variable var_1 after the assignment:",var_1.read_value())

Value of the variable var_1: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Value of the variable var_1 after the assignment: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [ ]:
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
#Variable addition
var_1.assign_add(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [ ]:
#Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.
tensor_h = tf.random.normal([4,100,100,3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 8.21367979e-01, -2.41182208e+00,  6.41544282e-01],
         [ 1.31715786e+00,  1.32196057e+00, -8.09203804e-01],
         [-1.09738469e+00,  3.01886201e-01, -6.92484202e-03],
         ...,
         [ 6.95406497e-02, -1.70969293e-02,  2.29363650e-01],
         [ 5.49655497e-01, -8.18093300e-01,  4.13183033e-01],
         [ 1.28793216e+00, -1.59119561e-01,  1.20102935e-01]],

        [[-5.52025795e-01, -1.85963362e-02, -9.14490700e-01],
         [-1.09432530e+00,  5.91208756e-01,  1.22050619e+00],
         [-1.41728997e-01, -9.85789225e-02, -9.96377170e-01],
         ...,
         [-2.59754330e-01,  2.64513230e+00,  9.51900125e-01],
         [ 7.20220923e-01,  4.50550467e-01,  5.49167812e-01],
         [-1.60962713e+00, -7.18665779e-01, -1.02476287e+00]],

        [[-1.47944897e-01, -1.77810520e-01, -8.49164009e-01],
         [ 1.22710682e-01, -3.50038737e-01, -1.89591193e+00],
         [ 2.20349252e-01, -9.32799578e-01

In [ ]:
#Extract the first image.
tensor_h[3,:,:,1]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[ 0.821368  , -2.411822  ,  0.6415443 ],
        [ 1.3171579 ,  1.3219606 , -0.8092038 ],
        [-1.0973847 ,  0.3018862 , -0.00692484],
        ...,
        [ 0.06954065, -0.01709693,  0.22936365],
        [ 0.5496555 , -0.8180933 ,  0.41318303],
        [ 1.2879322 , -0.15911956,  0.12010293]],

       [[-0.5520258 , -0.01859634, -0.9144907 ],
        [-1.0943253 ,  0.59120876,  1.2205062 ],
        [-0.141729  , -0.09857892, -0.99637717],
        ...,
        [-0.25975433,  2.6451323 ,  0.9519001 ],
        [ 0.7202209 ,  0.45055047,  0.5491678 ],
        [-1.6096271 , -0.7186658 , -1.0247629 ]],

       [[-0.1479449 , -0.17781052, -0.849164  ],
        [ 0.12271068, -0.35003874, -1.8959119 ],
        [ 0.22034925, -0.9327996 , -1.3938261 ],
        ...,
        [ 0.13924791, -1.638179  ,  0.00623046],
        [-0.66793984, -0.72279596,  2.5072312 ],
        [ 0.06945138,  0.11898614, -0.02567044]],

       ...,

     

In [ ]:
#Slice data from the last element.
tensor_h[::-1]

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 6.08968377e-01, -8.80480051e-01, -1.52339220e+00],
         [ 1.96542490e+00, -4.65342343e-01,  1.62882969e-01],
         [-1.06872164e-01,  4.88726139e-01,  1.50733161e+00],
         ...,
         [-8.11460853e-01, -3.91837478e-01, -1.14966238e+00],
         [ 8.13602030e-01, -6.03945911e-01, -4.76235688e-01],
         [ 1.23345268e+00,  6.85843468e-01,  1.34535241e+00]],

        [[-2.65667647e-01, -1.21598780e+00,  1.56408161e-01],
         [-7.34865844e-01,  2.38641813e-01, -1.06512749e+00],
         [ 1.23239803e+00,  2.69207358e-01, -3.16525626e+00],
         ...,
         [-8.40115070e-01, -2.83156300e+00,  1.37164402e+00],
         [-2.07471824e+00, -1.76359519e-01, -4.96087283e-01],
         [-1.36789882e+00,  1.57308936e-01,  3.59044224e-01]],

        [[ 2.28925204e+00, -1.06716566e-01, -8.36821854e-01],
         [ 2.40143389e-01, -1.10799682e+00,  4.87607606e-02],
         [ 7.05548465e-01,  9.15779531e-01

In [ ]:
#Obtain the pixel in the position [20,40] in the second channel of the first image.
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.6311625>

In [ ]:
#Extract the first, second, and fourth images from tensor_h ([4,100,100,3]).
indices = [0,1,3]
tf.gather(tensor_h,axis=0,indices=indices)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[ 8.21367979e-01, -2.41182208e+00,  6.41544282e-01],
         [ 1.31715786e+00,  1.32196057e+00, -8.09203804e-01],
         [-1.09738469e+00,  3.01886201e-01, -6.92484202e-03],
         ...,
         [ 6.95406497e-02, -1.70969293e-02,  2.29363650e-01],
         [ 5.49655497e-01, -8.18093300e-01,  4.13183033e-01],
         [ 1.28793216e+00, -1.59119561e-01,  1.20102935e-01]],

        [[-5.52025795e-01, -1.85963362e-02, -9.14490700e-01],
         [-1.09432530e+00,  5.91208756e-01,  1.22050619e+00],
         [-1.41728997e-01, -9.85789225e-02, -9.96377170e-01],
         ...,
         [-2.59754330e-01,  2.64513230e+00,  9.51900125e-01],
         [ 7.20220923e-01,  4.50550467e-01,  5.49167812e-01],
         [-1.60962713e+00, -7.18665779e-01, -1.02476287e+00]],

        [[-1.47944897e-01, -1.77810520e-01, -8.49164009e-01],
         [ 1.22710682e-01, -3.50038737e-01, -1.89591193e+00],
         [ 2.20349252e-01, -9.32799578e-01

In [ ]:
#Extract the pixel in [1,1] from the first dimension of the first image and the pixel in [2,2] from the first dimension of the second image in tensot_h ([4,100,100,3]).
indices = [[0,1,1,0],[1,1,1,0]]
tf.gather_nd(tensor_h,indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.0943253,  1.1746857], dtype=float32)>

In [ ]:
const_d_1 = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32)
#Three common methods for displaying a dimension:
print(const_d_1.shape)
print(const_d_1.get_shape())
print(tf.shape(const_d_1))#The output is a tensor. The value of the tensor indicates the size of the tensor dimension to be displayed.

(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [ ]:
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)
tf.reshape(reshape_1, (3,2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
expand_sample_1 = tf.random.normal([100,100,3], seed=1)
print("size of the original data:",expand_sample_1.shape)
print("add a dimension before the first dimension (axis = 0): ",tf.expand_dims(expand_sample_1, axis=0).shape)
print("add a dimension before the second dimension (axis = 1): ",tf.expand_dims(expand_sample_1, axis=1).shape)
print("add a dimension after the last dimension (axis = –1): ",tf.expand_dims(expand_sample_1, axis=-1).shape)

size of the original data: (100, 100, 3)
add a dimension before the first dimension (axis = 0):  (1, 100, 100, 3)
add a dimension before the second dimension (axis = 1):  (100, 1, 100, 3)
add a dimension after the last dimension (axis = –1):  (100, 100, 3, 1)


In [ ]:
#Input the tensor to be transposed, and call tf.transpose.
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("size of the original data:",trans_sample_1.shape)
transposed_sample_1 = tf.transpose(trans_sample_1)
print("size of transposed data:",transposed_sample_1.shape)

size of the original data: (2, 3)
size of transposed data: (3, 2)


In [ ]:
#broadcast_to is used to broadcast data from a low dimension to a high dimension
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
print("original data:",broadcast_sample_1.numpy())
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])
print("broadcasted data:",broadcasted_sample_1.numpy())

original data: [1 2 3 4 5 6]
broadcasted data: [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [ ]:
#During the operation, if two arrays have different shapes, TensorFlow automatically triggers the broadcast mechanism as NumPy does.
a = tf.constant([[ 0, 0, 0],
[10,10,10],
[20,20,20],
[30,30,30]])
b = tf.constant([1,2,3])
print(a + b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


In [ ]:
#Arithmetic Operations on Tensors
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]], dtype=int32)>

In [ ]:
#Tensor Concatenation and Splitting
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("sizes of the original data:",concat_sample_1.shape,concat_sample_2.shape)
concated_sample_3 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("size of the concatenated data:",concated_sample_1.shape)

sizes of the original data: (4, 100, 100, 3) (40, 100, 100, 3)
size of the concatenated data: (44, 100, 100, 3)


In [ ]:
#Split data based on the first dimension and output the split data in a list.
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)
#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=-1)
print("size of the concatenated data:",stacked_sample_1.shape)



sizes of the original data:  (100, 100, 3) (100, 100, 3)
size of the concatenated data: (2, 100, 100, 3)


In [ ]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[ 4.1942909e-01, -1.1902192e+00,  1.7001216e+00],
         [ 1.4061608e+00, -1.7696097e-01,  1.0432444e+00],
         [ 1.2415276e+00,  1.7448488e-01,  8.2712722e-01],
         ...,
         [-7.2288901e-01, -1.8062683e+00, -7.0916545e-01],
         [ 7.4826461e-01,  4.3371058e-01,  9.6277750e-01],
         [ 2.7330825e-01,  3.1785572e-01,  3.6762878e-01]],
 
        [[ 1.4118989e+00, -1.1746178e+00, -1.5725337e+00],
         [ 7.0950031e-01, -4.0261298e-01, -2.1714585e+00],
         [-9.3578398e-01, -6.0696518e-01, -1.3218167e+00],
         ...,
         [-4.3943156e-02,  4.9189672e-01, -1.4217677e+00],
         [-6.7762846e-01, -8.3079159e-02, -1.1025522e+00],
         [ 8.1247978e-02, -2.2288767e-01, -1.8079740e+00]],
 
        [[ 2.2979045e+00,  2.5026817e+00, -1.5965415e+00],
         [ 1.0092254e+00, -9.3993258e-01,  1.5509719e+00],
         [ 1.0895561e+00, -1.4469604e-01, -1.5905944e-03],
         ...,
         [-

In [ ]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[ 4.1942909e-01, -1.1902192e+00,  1.7001216e+00],
         [ 1.4061608e+00, -1.7696097e-01,  1.0432444e+00],
         [ 1.2415276e+00,  1.7448488e-01,  8.2712722e-01],
         ...,
         [-7.2288901e-01, -1.8062683e+00, -7.0916545e-01],
         [ 7.4826461e-01,  4.3371058e-01,  9.6277750e-01],
         [ 2.7330825e-01,  3.1785572e-01,  3.6762878e-01]],
 
        [[ 1.4118989e+00, -1.1746178e+00, -1.5725337e+00],
         [ 7.0950031e-01, -4.0261298e-01, -2.1714585e+00],
         [-9.3578398e-01, -6.0696518e-01, -1.3218167e+00],
         ...,
         [-4.3943156e-02,  4.9189672e-01, -1.4217677e+00],
         [-6.7762846e-01, -8.3079159e-02, -1.1025522e+00],
         [ 8.1247978e-02, -2.2288767e-01, -1.8079740e+00]],
 
        [[ 2.2979045e+00,  2.5026817e+00, -1.5965415e+00],
         [ 1.0092254e+00, -9.3993258e-01,  1.5509719e+00],
         [ 1.0895561e+00, -1.4469604e-01, -1.5905944e-03],
         ...,
         [-

In [ ]:
#Tensor Sorting
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

input tensor: [6 2 7 4 8 0 5 1 3 9]
tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]
indexes of elements in ascending order: [5 7 1 8 3 6 0 2 4 9]


Eager Execution of TensorFlow 2.x
Eager execution mode:
The eager execution mode of TensorFlow is a type of imperative programming, which is the same as native Python. When you perform a particular operation, the system immediately returns a result


In [ ]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2],
[3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [ ]:
#AutoGraph of TensorFlow 2.x
def simple_nn_layer(w,x,b):
  net = tf.matmul(w, x)+b
  y = tf.nn.relu(net)
  return y


In [ ]:
def simple_nn_layer(w,x,b):
  return tf.nn.relu(tf.matmul(w, x)+b)

In [ ]:
w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype='float32')
simple_nn_layer(w,x,b)

tf.Tensor(0.5, shape=(), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.4185088, 1.0470204, 1.017204 ],
       [1.4874439, 1.3561189, 1.062947 ],
       [1.5649743, 1.9185302, 1.1549277]], dtype=float32)>